### ISSUE TITLE
Posible corrección

### ISSUE THREAD

**Issue by marcocabrerahdez** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct10-async-fs-process-alu0101327372#1]
Estaba revisando los informes pendientes de calificar y me he dado cuenta que olvidé incluir el ejercicio 1 en el informe, es decir, el de la traza. El ejercicio lo tengo hecho pero está en local. ¿Sería posible modificarlo y añadirlo aunque esté fuera de fecha?@esegredo

**Comment by esegredo** [comment]
Añádelo.
